spring:
  profiles:
    active:
      -dev

---
spring:
  profiles: dev
  application:
    name: config-client-dev
    
userName: pingyuan    

---
spring:
  profiles: test
  application:
    name: config-client-test

---
spring:
  profiles: pro
  application:
    name: config-client-pro
